### ISSUE TITLE
LOC7364USA and LOC0296IHA

### ISSUE THREAD

**Issue by nafisa-valieva** [BetaMasaheft/Places#128]
Hello. I have found two seemingly identical placename ids for the United States of America,  LOC7364USA and LOC0296IHA, one created by Dorothea (more elaborated) and one created by Alessandro Gori.  Are they different? For the moment I will use LOC7364USA, but it would be helpful, in case these two records are different, to make this difference more clear.

**Comment by nafisa-valieva** [comment]
(I have tried to unassign myself, but somehow it did not work for me.)

**Comment by eu-genia** [comment]
Please disregard any ID containing IHA. There are from IslHornAfr project and stay as they are, we do not use them. 
All issues must be opened under Documentation, thank you.
